name: buildings-blocks-01

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello"
  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: |
          echo "i will succes"
          exit 0
      - name: Say bye
        run : echo "bye"