name: 07-using expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print start-up data
              if: ${{ inputs.debug }}
              run: |
                    echo "Triggred by:${{ github.event_name }}"
                    echo "Branch: ${{ github.ref}}"
                    echo "Commit SHA: ${{ github.sha}}"
                    echo "Runner OS: ${{ runner.os}}"

            - name: Print When triggered from main
              if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
              run: |
                        echo "I was triggered from the main"
            - name: Greeting
              run: |
                echo "Hello World"